elements = {
    'username': ['NAME', 'username'],
    'password': ['NAME', 'password'],
    'admin_setting': ['LINK_TEXT', 'admin'],
    'users': ['LINK_TEXT', 'Users'],
    'users_action_button': ['XPATH', "/html/body/div[3]/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/button"],
    'add_user': ['ID', 'click_manual'],
    'firstName': ['NAME', 'first_name'],
    'lastName': ['NAME', 'last_name'],
    'username_': ['NAME', 'username'],
    'email': ['ID', 'email'],
    'role': ['NAME', 'role'],
    'language': ['NAME', 'language'],
    'reset': ['ID', 'reset'],
    'password_': ['ID', 'password'],
    'password_2': ['ID', 'password_confirmation'],
    'department': ['NAME', 'department'],
    'status': ['NAME', 'status'],
    'save_user': ['XPATH', '//*[@id="form_add_user"]/div[3]/button[2]'],

    'logout': ['LINK_TEXT', 'Log Out'],
    'training': ['LINK_TEXT', 'Training'],
    'campaigns': ['LINK_TEXT', 'Campaigns'],
    'create_campaign': ['LINK_TEXT', 'Create Campaign'],
    'title': ['NAME', 'title'],
    'exam': ['ID', 'exam'],
    'save_campaign': ['CSS_SELECTOR', '#form_add_campaign > div.form-actions.right > button.btn.blue'],
    'table': ['TAG_NAME', 'table'],
    'admin': ['XPATH', '/html/body/div[1]/div/div[2]/div/ul[1]/li/a'],
    'default_campaign': ['NAME', 'default_campaign'],
    'home': ['LINK_TEXT', 'Home'],
    'departments': ['LINK_TEXT', 'Departments'],
    'click_department': ['ID', 'click_department'],
    'table_departments_filter': ['ID', 'table_departments_filter'],
    'table_users_filter': ['ID', 'table_users_filter'],
    'input-sm': ['CLASS_NAME', 'input-sm'],
    'dataTables_info': ['CLASS_NAME', 'dataTables_info'],
    'edit_user': ['LINK_TEXT', 'Edit'],
    'delete_user': ['LINK_TEXT', 'Delete'],
    'ok_btn': ['CLASS_NAME', 'btn-primary']

}